FROM nginx:1.10.3

RUN useradd -d /home/isucon -m isucon
RUN rm -f /etc/nginx/conf.d/default.conf

USER isucon
ENV GOPATH=${HOME}/go
WORKDIR /home/isucon
RUN mkdir ${HOME}/webapp
COPY isucon7-final/webapp/public /home/isucon/webapp/public

USER root
RUN chown -R isucon: /home/isucon/webapp
ENTRYPOINT ["nginx", "-g", "daemon off;"]
