FROM golang:1.9.2

RUN useradd -d /home/isucon -m isucon
RUN mkdir -p /home/isucon/go/src
COPY isucon7-final/webapp/go/src/app /home/isucon/go/src/app
RUN chown -R isucon: /home/isucon/go

USER isucon
ENV GOPATH=/home/isucon/go PATH=/home/isucon/go/bin:$PATH
WORKDIR /home/isucon
RUN go get -u github.com/golang/dep/cmd/dep

WORKDIR /home/isucon/go/src/app
RUN dep ensure && go build

EXPOSE 5000

ENTRYPOINT ["./app"]